apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-registry
  namespace: default
  labels:
    k8s-app: nginx-registry
spec:
  replicas: 1
  selector:
    k8s-app: nginx-registry
  template:
    metadata:
      labels:
        k8s-app: nginx-registry
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: nginx-registry
        image: ztsyed/nginx
        ports:
        - containerPort: 8080
          name: nginx
          protocol: TCP