apiVersion: v1
kind: Service
metadata:
  name: nginx-registry
  namespace: default
  labels:
    k8s-app: nginx-registry
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "DockerRegistry"
spec:
  selector:
    k8s-app: nginx-registry
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP