apiVersion: v1
kind: ReplicationController
metadata:
  name: docker-registry-v2
  namespace: default
  labels:
    k8s-app: docker-registry
    version: v2
spec:
  replicas: 1
  selector:
    k8s-app: docker-registry
    version: v2
  template:
    metadata:
      labels:
        k8s-app: docker-registry
        version: v2
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP