apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: default
  labels:
    k8s-app: docker-registry
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "DockerRegistry"
spec:
  selector:
    k8s-app: docker-registry
  ports:
  - port: 5050
    targetPort: 5000
    protocol: TCP